version: "3.9"
services:
  stirling-pdf:
    container_name: Stirling-PDF
    image: frooodle/s-pdf
    security_opt:
      - "no-new-privileges:true"  # Ge채ndert, um den Wert als String zu setzen
    healthcheck:
     test: curl -f http://localhost:8080/ || exit 1
    ports:
      - 7890:8080
    volumes:
      - /home/georg/data/stirling/data:/usr/share/tesseract-ocr/4.00/tessdata:rw
      - /home/georg/data/stirling/config:/configs:rw
      - /home/georg/data/stirling/customFiles:/customFiles:rw
      - /home/georg/data/stirling/logs:/logs:rw
    environment:
      DOCKER_ENABLE_SECURITY: "true"  # Ge채ndert, um den Wert als String zu setzen
      SYSTEM_DEFAULTLOCALE: de_DE # or fr_FR or en_US
      UI_APPNAME: "StirlingPDF"
      UI_APPNAMENAVBAR: "Stirling PDF"
      SYSTEM_MAXFILESIZE: "5000"  # Ge채ndert, um den Wert als String zu setzen
      METRICS_ENABLED: "true"
      SYSTEM_GOOGLEVISIBILITY: "false"  # Ge채ndert, um den Wert als String zu setzen
    restart: on-failure:5