- hosts: "all"
  become: true
  tasks:

    - name: "apt update"
      apt:
        update_cache: "yes"

    - name: "apt upgrade"
      apt:
        upgrade: "safe"

    - name: "apt autoclean"
      apt:
        autoclean: "yes"
