- hosts: "all"
  become: true
  tasks:

    - name: "SSH-Port ändern"
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "Port 15684"
        line: "Port 22"

    - name: "SSHD neu starten"
      service:
        name: "sshd"
        state: "restarted"
