- hosts: "all"
  become: true

  vars:
    PROJECT_DIR: "/home/docker/projects/paperless-ngx/"

  tasks:

    - name: "filezilla installieren"
      apt:
        name: "filezilla"

    - name: "proftpd-basic installieren"
      apt:
        name: "proftpd-basic"

    - name: Erstelle und fülle eine Datei
      ansible.builtin.copy:
        content: |
          <Global>
            RequireValidShell off
          </Global>
          # If desired turn off IPv6
          UseIPv6 off
          # Default directory is ftpusers home
          # DefaultRoot ~ ftpuser
          # Limit login to the ftpuser group
          <Limit LOGIN>
            DenyGroup !ftpuser
          </Limit>
        dest: /etc/proftpd/conf.d/ftp.conf

    - name: "restart proftpd"
      shell: systemctl restart proftpd

    - name: "add ftpuser group if it does not exist"
      ansible.builtin.group:
        name: ftpuser
        state: present
      ignore_errors: yes

    - name: "userrechte auf paperless ausweiten"
      shell: usermod -aG ftpuser paperless

    - name: "Erstelle für paperless-ngx redisdata Ordner"
      shell: mkdir -p /home/georg/data/paperless-ngx/redisdata

    - name: Erstelle für paperless-ngx data Ordner
      shell: mkdir -p /home/georg/data/paperless-ngx/data

    - name: Erstelle für paperless-ngx media Ordner
      shell: mkdir -p /home/georg/data/paperless-ngx/media

    - name: Erstelle für paperless-ngx export Ordner
      shell: mkdir -p /home/paperless/export

    - name: Erstelle für paperless-ngx consume Ordner
      shell: mkdir -p /home/paperless/consume

    - name: "Delete Old Project Directory"
      file:
        state: "absent"
        path: "{{ PROJECT_DIR }}"  # Setzen Sie den Pfad hier entsprechend Ihrer Konfiguration

    - name: "Copy Project Directory"
      copy:
        src: "./docker/paperless-ngx/"  # Stellen Sie sicher, dass der Quellpfad korrekt ist
        dest: "{{ PROJECT_DIR }}"   # Setzen Sie den Zielordner entsprechend Ihrer Konfiguration

    - name: "Init paperless-ngx"
      docker_compose:
        project_src: "{{ PROJECT_DIR }}"  # Setzen Sie den Pfad zum Docker-Compose-File
        restarted: "yes"
        pull: "yes"
#
