- hosts: "all"
  become: true

  vars:
    PROJECT_DIR: "/home/docker/projects/nextcloud/"

  tasks:

    - name: "Delete Old Project Directory"
      file:
        state: "absent"
        path: "{{ PROJECT_DIR }}"  # Setzen Sie den Pfad hier entsprechend Ihrer Konfiguration

    - name: "Copy Project Directory"
      copy:
        src: "./docker/nextcloud/"  # Stellen Sie sicher, dass der Quellpfad korrekt ist
        dest: "{{ PROJECT_DIR }}"   # Setzen Sie den Zielordner entsprechend Ihrer Konfiguration

    - name: "Init nextcloud"
      docker_compose:
        project_src: "{{ PROJECT_DIR }}"  # Setzen Sie den Pfad zum Docker-Compose-File
        restarted: "yes"
        pull: "yes"
