- hosts: "all"
  become: true
  tasks:

    - name: "Init Ghost"
      docker_compose:
        project_name: "ghost"
        restarted: "yes"
        pull: "yes"

        definition:

          networks:
            default:
            proxynet:
              external: true

          services:
            ghost:
              image: "ghost:5-alpine"
              restart: "unless-stopped"
              environment:
                url: "https://ghost.demo01.pidahmen.duckdns.org"
              networks:
                default:
                proxynet:
                  aliases:
                    - ghost
              volumes:
                - "/home/docker/data/ghost/content:/var/lib/ghost/content"
