version: '3.8'

services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - bridge
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "/home/georg/data/pmnginx/data:/data"
      - "/home/georg/data/pmnginx/cert:/etc/letsencrypt"
    environment:
      TZ: Europe/Berlin
    
networks:
  bridge: